#!/usr/bin/env python3
# This file is a part of marzer/poxy and is subject to the terms of the MIT license.
# Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
# See https://github.com/marzer/poxy/blob/master/LICENSE for the full license text.
# SPDX-License-Identifier: MIT
"""
Default values for project configuration (built-in macros, code-block patterns, aliases, etc.).
Pure data, extracted verbatim from project.py.
"""

from .utils import *


class Defaults:
    inline_namespaces = {r'std::(?:literals::)?(?:chrono|complex|string|string_view)_literals'}
    macros = {
        r'NDEBUG': 1,
        r'DOXYGEN': 1,
        r'__DOXYGEN__': 1,
        r'__doxygen__': 1,
        r'__POXY__': 1,
        r'__poxy__': 1,
        r'__has_include(...)': 0,
        r'__has_attribute(...)': 0,
        r'__has_builtin(...)': 0,
        r'__has_feature(...)': 0,
        r'__has_cpp_attribute(...)': 999999,
        r'POXY_IMPLEMENTATION_DETAIL(...)': r'poxyimplementationdetailimplplaceholder',
        r'POXY_IGNORE(...)': r'',
    }
    cpp_builtin_macros = {
        1998: {r'__cplusplus': r'199711L', r'__cpp_rtti': 199711, r'__cpp_exceptions': 199711},
        2003: dict(),  # apparently?
        2011: {
            r'__cplusplus': r'201103L',
            r'__cpp_unicode_characters': 200704,
            r'__cpp_raw_strings': 200710,
            r'__cpp_unicode_literals': 200710,
            r'__cpp_user_defined_literals': 200809,
            r'__cpp_threadsafe_static_init': 200806,
            r'__cpp_lambdas': 200907,
            r'__cpp_constexpr': 200704,
            r'__cpp_range_based_for': 200907,
            r'__cpp_static_assert': 200410,
            r'__cpp_decltype': 200707,
            r'__cpp_attributes': 200809,
            r'__cpp_rvalue_references': 200610,
            r'__cpp_variadic_templates': 200704,
            r'__cpp_initializer_lists': 200806,
            r'__cpp_delegating_constructors': 200604,
            r'__cpp_nsdmi': 200809,
            r'__cpp_inheriting_constructors': 200802,
            r'__cpp_ref_qualifiers': 200710,
            r'__cpp_alias_templates': 200704,
        },
        2014: {
            r'__cplusplus': r'201402L',
            r'__cpp_binary_literals': 201304,
            r'__cpp_init_captures': 201304,
            r'__cpp_generic_lambdas': 201304,
            r'__cpp_sized_deallocation': 201309,
            r'__cpp_constexpr': 201304,
            r'__cpp_decltype_auto': 201304,
            r'__cpp_return_type_deduction': 201304,
            r'__cpp_aggregate_nsdmi': 201304,
            r'__cpp_variable_templates': 201304,
            r'__cpp_lib_integer_sequence': 201304,
            r'__cpp_lib_exchange_function': 201304,
            r'__cpp_lib_tuples_by_type': 201304,
            r'__cpp_lib_tuple_element_t': 201402,
            r'__cpp_lib_make_unique': 201304,
            r'__cpp_lib_transparent_operators': 201210,
            r'__cpp_lib_integral_constant_callable': 201304,
            r'__cpp_lib_transformation_trait_aliases': 201304,
            r'__cpp_lib_result_of_sfinae': 201210,
            r'__cpp_lib_is_final': 201402,
            r'__cpp_lib_is_null_pointer': 201309,
            r'__cpp_lib_chrono_udls': 201304,
            r'__cpp_lib_string_udls': 201304,
            r'__cpp_lib_generic_associative_lookup': 201304,
            r'__cpp_lib_null_iterators': 201304,
            r'__cpp_lib_make_reverse_iterator': 201402,
            r'__cpp_lib_robust_nonmodifying_seq_ops': 201304,
            r'__cpp_lib_complex_udls': 201309,
            r'__cpp_lib_quoted_string_io': 201304,
            r'__cpp_lib_shared_timed_mutex': 201402,
        },
        2017: {
            r'__cplusplus': r'201703L',
            r'__cpp_hex_float': 201603,
            r'__cpp_inline_variables': 201606,
            r'__cpp_aligned_new': 201606,
            r'__cpp_guaranteed_copy_elision': 201606,
            r'__cpp_noexcept_function_type': 201510,
            r'__cpp_fold_expressions': 201603,
            r'__cpp_capture_star_this': 201603,
            r'__cpp_constexpr': 201603,
            r'__cpp_if_constexpr': 201606,
            r'__cpp_range_based_for': 201603,
            r'__cpp_static_assert': 201411,
            r'__cpp_deduction_guides': 201703,
            r'__cpp_nontype_template_parameter_auto': 201606,
            r'__cpp_namespace_attributes': 201411,
            r'__cpp_enumerator_attributes': 201411,
            r'__cpp_inheriting_constructors': 201511,
            r'__cpp_variadic_using': 201611,
            r'__cpp_structured_bindings': 201606,
            r'__cpp_aggregate_bases': 201603,
            r'__cpp_nontype_template_args': 201411,
            r'__cpp_template_template_args': 201611,
            r'__cpp_lib_byte': 201603,
            r'__cpp_lib_hardware_interference_size': 201703,
            r'__cpp_lib_launder': 201606,
            r'__cpp_lib_uncaught_exceptions': 201411,
            r'__cpp_lib_as_const': 201510,
            r'__cpp_lib_make_from_tuple': 201606,
            r'__cpp_lib_apply': 201603,
            r'__cpp_lib_optional': 201606,
            r'__cpp_lib_variant': 201606,
            r'__cpp_lib_any': 201606,
            r'__cpp_lib_addressof_constexpr': 201603,
            r'__cpp_lib_raw_memory_algorithms': 201606,
            r'__cpp_lib_transparent_operators': 201510,
            r'__cpp_lib_enable_shared_from_this': 201603,
            r'__cpp_lib_shared_ptr_weak_type': 201606,
            r'__cpp_lib_shared_ptr_arrays': 201611,
            r'__cpp_lib_memory_resource': 201603,
            r'__cpp_lib_boyer_moore_searcher': 201603,
            r'__cpp_lib_invoke': 201411,
            r'__cpp_lib_not_fn': 201603,
            r'__cpp_lib_void_t': 201411,
            r'__cpp_lib_bool_constant': 201505,
            r'__cpp_lib_type_trait_variable_templates': 201510,
            r'__cpp_lib_logical_traits': 201510,
            r'__cpp_lib_is_swappable': 201603,
            r'__cpp_lib_is_invocable': 201703,
            r'__cpp_lib_has_unique_object_representations': 201606,
            r'__cpp_lib_is_aggregate': 201703,
            r'__cpp_lib_chrono': 201611,
            r'__cpp_lib_execution': 201603,
            r'__cpp_lib_parallel_algorithm': 201603,
            r'__cpp_lib_to_chars': 201611,
            r'__cpp_lib_string_view': 201606,
            r'__cpp_lib_allocator_traits_is_always_equal': 201411,
            r'__cpp_lib_incomplete_container_elements': 201505,
            r'__cpp_lib_map_try_emplace': 201411,
            r'__cpp_lib_unordered_map_try_emplace': 201411,
            r'__cpp_lib_node_extract': 201606,
            r'__cpp_lib_array_constexpr': 201603,
            r'__cpp_lib_nonmember_container_access': 201411,
            r'__cpp_lib_sample': 201603,
            r'__cpp_lib_clamp': 201603,
            r'__cpp_lib_gcd_lcm': 201606,
            r'__cpp_lib_hypot': 201603,
            r'__cpp_lib_math_special_functions': 201603,
            r'__cpp_lib_filesystem': 201703,
            r'__cpp_lib_atomic_is_always_lock_free': 201603,
            r'__cpp_lib_shared_mutex': 201505,
            r'__cpp_lib_scoped_lock': 201703,
        },
        2020: {
            r'__cplusplus': r'202002L',
            r'__cpp_aggregate_paren_init': 201902,
            r'__cpp_char8_t': 201811,
            r'__cpp_concepts': 202002,
            r'__cpp_conditional_explicit': 201806,
            r'__cpp_consteval': 201811,
            r'__cpp_constexpr': 202002,
            r'__cpp_constexpr_dynamic_alloc': 201907,
            r'__cpp_constexpr_in_decltype': 201711,
            r'__cpp_constinit': 201907,
            r'__cpp_deduction_guides': 201907,
            r'__cpp_designated_initializers': 201707,
            r'__cpp_generic_lambdas': 201707,
            r'__cpp_impl_coroutine': 201902,
            r'__cpp_impl_destroying_delete': 201806,
            r'__cpp_impl_three_way_comparison': 201907,
            r'__cpp_init_captures': 201803,
            r'__cpp_lib_array_constexpr': 201811,
            r'__cpp_lib_assume_aligned': 201811,
            r'__cpp_lib_atomic_flag_test': 201907,
            r'__cpp_lib_atomic_float': 201711,
            r'__cpp_lib_atomic_lock_free_type_aliases': 201907,
            r'__cpp_lib_atomic_ref': 201806,
            r'__cpp_lib_atomic_shared_ptr': 201711,
            r'__cpp_lib_atomic_value_initialization': 201911,
            r'__cpp_lib_atomic_wait': 201907,
            r'__cpp_lib_barrier': 201907,
            r'__cpp_lib_bind_front': 201907,
            r'__cpp_lib_bit_cast': 201806,
            r'__cpp_lib_bitops': 201907,
            r'__cpp_lib_bounded_array_traits': 201902,
            r'__cpp_lib_char8_t': 201907,
            r'__cpp_lib_chrono': 201907,
            r'__cpp_lib_concepts': 202002,
            r'__cpp_lib_constexpr_algorithms': 201806,
            r'__cpp_lib_constexpr_complex': 201711,
            r'__cpp_lib_constexpr_dynamic_alloc': 201907,
            r'__cpp_lib_constexpr_functional': 201907,
            r'__cpp_lib_constexpr_iterator': 201811,
            r'__cpp_lib_constexpr_memory': 201811,
            r'__cpp_lib_constexpr_numeric': 201911,
            r'__cpp_lib_constexpr_string': 201907,
            r'__cpp_lib_constexpr_string_view': 201811,
            r'__cpp_lib_constexpr_tuple': 201811,
            r'__cpp_lib_constexpr_utility': 201811,
            r'__cpp_lib_constexpr_vector': 201907,
            r'__cpp_lib_coroutine': 201902,
            r'__cpp_lib_destroying_delete': 201806,
            r'__cpp_lib_endian': 201907,
            r'__cpp_lib_erase_if': 202002,
            r'__cpp_lib_execution': 201902,
            r'__cpp_lib_format': 201907,
            r'__cpp_lib_generic_unordered_lookup': 201811,
            r'__cpp_lib_int_pow2': 202002,
            r'__cpp_lib_integer_comparison_functions': 202002,
            r'__cpp_lib_interpolate': 201902,
            r'__cpp_lib_is_constant_evaluated': 201811,
            r'__cpp_lib_is_layout_compatible': 201907,
            r'__cpp_lib_is_nothrow_convertible': 201806,
            r'__cpp_lib_is_pointer_interconvertible': 201907,
            r'__cpp_lib_jthread': 201911,
            r'__cpp_lib_latch': 201907,
            r'__cpp_lib_list_remove_return_type': 201806,
            r'__cpp_lib_math_constants': 201907,
            r'__cpp_lib_polymorphic_allocator': 201902,
            r'__cpp_lib_ranges': 201911,
            r'__cpp_lib_remove_cvref': 201711,
            r'__cpp_lib_semaphore': 201907,
            r'__cpp_lib_shared_ptr_arrays': 201707,
            r'__cpp_lib_shift': 201806,
            r'__cpp_lib_smart_ptr_for_overwrite': 202002,
            r'__cpp_lib_source_location': 201907,
            r'__cpp_lib_span': 202002,
            r'__cpp_lib_ssize': 201902,
            r'__cpp_lib_starts_ends_with': 201711,
            r'__cpp_lib_string_view': 201803,
            r'__cpp_lib_syncbuf': 201803,
            r'__cpp_lib_three_way_comparison': 201907,
            r'__cpp_lib_to_address': 201711,
            r'__cpp_lib_to_array': 201907,
            r'__cpp_lib_type_identity': 201806,
            r'__cpp_lib_unwrap_ref': 201811,
            r'__cpp_modules': 201907,
            r'__cpp_nontype_template_args': 201911,
            r'__cpp_using_enum': 201907,
        },
        2023: {
            r'__cplusplus': r'202300L',
            r'__cpp_constexpr': 202110,
            r'__cpp_explicit_this_parameter': 202110,
            r'__cpp_if_consteval': 202106,
            r'__cpp_lib_adaptor_iterator_pair_constructor': 202106,
            r'__cpp_lib_allocate_at_least': 202106,
            r'__cpp_lib_associative_heterogeneous_erasure': 202110,
            r'__cpp_lib_byteswap': 202110,
            r'__cpp_lib_constexpr_typeinfo': 202106,
            r'__cpp_lib_format': 202110,
            r'__cpp_lib_invoke_r': 202106,
            r'__cpp_lib_is_scoped_enum': 202011,
            r'__cpp_lib_monadic_optional': 202110,
            r'__cpp_lib_move_only_function': 202110,
            r'__cpp_lib_optional': 202106,
            r'__cpp_lib_out_ptr': 202106,
            r'__cpp_lib_ranges': 202110,
            r'__cpp_lib_ranges_starts_ends_with': 202106,
            r'__cpp_lib_ranges_zip': 202110,
            r'__cpp_lib_spanstream': 202106,
            r'__cpp_lib_stacktrace': 202011,
            r'__cpp_lib_stdatomic_h': 202011,
            r'__cpp_lib_string_contains': 202011,
            r'__cpp_lib_string_resize_and_overwrite': 202110,
            r'__cpp_lib_to_underlying': 202102,
            r'__cpp_lib_variant': 202106,
            r'__cpp_multidimensional_subscript': 202110,
            r'__cpp_size_t_suffix': 202011,
        },
        2026: {r'__cplusplus': r'202600L'},
        2029: {r'__cplusplus': r'202900L'},
    }
    autolinks = {
        # builtins
        r'const_cast': r'https://en.cppreference.com/w/cpp/language/const_cast',
        r'dynamic_cast': r'https://en.cppreference.com/w/cpp/language/dynamic_cast',
        r'reinterpret_cast': r'https://en.cppreference.com/w/cpp/language/reinterpret_cast',
        r'static_cast': r'https://en.cppreference.com/w/cpp/language/static_cast',
        r'(?:_Float|__fp)16s?': r'https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html',
        r'(?:_Float|__float)(128|80)s?': r'https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html',
        r'(?:wchar|char(?:8|16|32))_ts?': r'https://en.cppreference.com/w/cpp/language/types#Character_types',
        regex_trie(
            r'__cplusplus',  #
            r'__FILE__',
            r'__LINE__',
            r'__DATE__',
            r'__TIME__',
            r'__STDC__',
            r'__STDC_HOSTED__',
            r'__STDC_VERSION__',
            r'__STDC_ISO_10646__',
            r'__STDC_MB_MIGHT_NEQ_WC__',
            r'__STDCPP_THREADS__',
            r'__STDCPP_DEFAULT_NEW_ALIGNMENT__',
            r'__STDCPP_STRICT_POINTER_SAFETY__',
        ): r'https://en.cppreference.com/w/cpp/preprocessor/replace',
        # standard library
        r'std::assume_aligned(?:\(\))?': r'https://en.cppreference.com/w/cpp/memory/assume_aligned',
        r'(?:std::)?nullptr_t': r'https://en.cppreference.com/w/cpp/types/nullptr_t',
        r'(?:std::)?ptrdiff_t': r'https://en.cppreference.com/w/cpp/types/ptrdiff_t',
        r'(?:std::)?size_t': r'https://en.cppreference.com/w/cpp/types/size_t',
        r'(?:std::)?u?int(?:_fast|_least)?(?:8|16|32|64)_ts?': r'https://en.cppreference.com/w/cpp/types/integer',
        r'(?:std::)?u?int(?:max|ptr)_t': r'https://en.cppreference.com/w/cpp/types/integer',
        r'\s(?:<|&lt;)fstream(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/fstream',
        r'\s(?:<|&lt;)iosfwd(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/iosfwd',
        r'\s(?:<|&lt;)iostream(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/iostream',
        r'\s(?:<|&lt;)sstream(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/sstream',
        r'\s(?:<|&lt;)string(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/string',
        r'\s(?:<|&lt;)string_view(?:>|&gt;)': r'https://en.cppreference.com/w/cpp/header/string_view',
        r'std::(?:basic_|w)?fstreams?': r'https://en.cppreference.com/w/cpp/io/basic_fstream',
        r'std::(?:basic_|w)?ifstreams?': r'https://en.cppreference.com/w/cpp/io/basic_ifstream',
        r'std::(?:basic_|w)?iostreams?': r'https://en.cppreference.com/w/cpp/io/basic_iostream',
        r'std::(?:basic_|w)?istreams?': r'https://en.cppreference.com/w/cpp/io/basic_istream',
        r'std::(?:basic_|w)?istringstreams?': r'https://en.cppreference.com/w/cpp/io/basic_istringstream',
        r'std::(?:basic_|w)?ofstreams?': r'https://en.cppreference.com/w/cpp/io/basic_ofstream',
        r'std::(?:basic_|w)?ostreams?': r'https://en.cppreference.com/w/cpp/io/basic_ostream',
        r'std::(?:basic_|w)?ostringstreams?': r'https://en.cppreference.com/w/cpp/io/basic_ostringstream',
        r'std::(?:basic_|w)?stringstreams?': r'https://en.cppreference.com/w/cpp/io/basic_stringstream',
        r'std::(?:basic_|w|u(?:8|16|32))?string_views?': r'https://en.cppreference.com/w/cpp/string/basic_string_view',
        r'std::(?:basic_|w|u(?:8|16|32))?strings?': r'https://en.cppreference.com/w/cpp/string/basic_string',
        r'std::[fl]?abs[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/abs',
        r'std::acos[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/acos',
        r'std::add_[lr]value_reference(?:_t)?': r'https://en.cppreference.com/w/cpp/types/add_reference',
        r'std::add_(?:cv|const|volatile)(?:_t)?': r'https://en.cppreference.com/w/cpp/types/add_cv',
        r'std::add_pointer(?:_t)?': r'https://en.cppreference.com/w/cpp/types/add_pointer',
        r'std::allocators?': r'https://en.cppreference.com/w/cpp/memory/allocator',
        r'std::arrays?': r'https://en.cppreference.com/w/cpp/container/array',
        r'std::as_(writable_)?bytes(?:\(\))?': r'https://en.cppreference.com/w/cpp/container/span/as_bytes',
        r'std::asin[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/asin',
        r'std::atan2[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/atan2',
        r'std::atan[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/atan',
        r'std::bad_alloc': r'https://en.cppreference.com/w/cpp/memory/new/bad_alloc',
        r'std::basic_ios': r'https://en.cppreference.com/w/cpp/io/basic_ios',
        r'std::bit_cast(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/bit_cast',
        r'std::bit_ceil(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/bit_ceil',
        r'std::bit_floor(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/bit_floor',
        r'std::bit_width(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/bit_width',
        r'std::bytes?': r'https://en.cppreference.com/w/cpp/types/byte',
        r'std::ceil[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/ceil',
        r'std::char_traits': r'https://en.cppreference.com/w/cpp/string/char_traits',
        r'std::chrono::durations?': r'https://en.cppreference.com/w/cpp/chrono/duration',
        r'std::clamp(?:\(\))?': r'https://en.cppreference.com/w/cpp/algorithm/clamp',
        r'std::conditional(?:_t)?': r'https://en.cppreference.com/w/cpp/types/conditional',
        r'std::cos[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/cos',
        r'std::countl_one(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/countl_one',
        r'std::countl_zero(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/countl_zero',
        r'std::countr_one(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/countr_one',
        r'std::countr_zero(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/countr_zero',
        r'std::enable_if(?:_t)?': r'https://en.cppreference.com/w/cpp/types/enable_if',
        r'std::exceptions?': r'https://en.cppreference.com/w/cpp/error/exception',
        r'std::expecteds?': r'https://en.cppreference.com/w/cpp/utility/expected',
        r'std::floor[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/floor',
        r'std::fpos': r'https://en.cppreference.com/w/cpp/io/fpos',
        r'std::has_single_bit(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/has_single_bit',
        r'std::hash': r'https://en.cppreference.com/w/cpp/utility/hash',
        r'std::initializer_lists?': r'https://en.cppreference.com/w/cpp/utility/initializer_list',
        r'std::integral_constants?': r'https://en.cppreference.com/w/cpp/types/integral_constant',
        r'std::ios(?:_base)?': r'https://en.cppreference.com/w/cpp/io/ios_base',
        r'std::is_(?:nothrow_)?convertible(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_convertible',
        r'std::is_(?:nothrow_)?invocable(?:_r)?': r'https://en.cppreference.com/w/cpp/types/is_invocable',
        r'std::is_base_of(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_base_of',
        r'std::is_constant_evaluated(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/is_constant_evaluated',
        r'std::is_enum(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_enum',
        r'std::is_floating_point(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_floating_point',
        r'std::is_integral(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_integral',
        r'std::is_pointer(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_pointer',
        r'std::is_reference(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_reference',
        r'std::is_same(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_same',
        r'std::is_signed(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_signed',
        r'std::is_unsigned(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_unsigned',
        r'std::is_void(?:_v)?': r'https://en.cppreference.com/w/cpp/types/is_void',
        r'std::launder(?:\(\))?': r'https://en.cppreference.com/w/cpp/utility/launder',
        r'std::lerp(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/lerp',
        r'std::maps?': r'https://en.cppreference.com/w/cpp/container/map',
        r'std::max(?:\(\))?': r'https://en.cppreference.com/w/cpp/algorithm/max',
        r'std::min(?:\(\))?': r'https://en.cppreference.com/w/cpp/algorithm/min',
        r'std::numeric_limits::min(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/min',
        r'std::numeric_limits::lowest(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/lowest',
        r'std::numeric_limits::max(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/max',
        r'std::numeric_limits::epsilon(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon',
        r'std::numeric_limits::round_error(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/round_error',
        r'std::numeric_limits::infinity(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/infinity',
        r'std::numeric_limits::quiet_NaN(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/quiet_NaN',
        r'std::numeric_limits::signaling_NaN(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/signaling_NaN',
        r'std::numeric_limits::denorm_min(?:\(\))?': r'https://en.cppreference.com/w/cpp/types/numeric_limits/denorm_min',
        r'std::numeric_limits': r'https://en.cppreference.com/w/cpp/types/numeric_limits',
        r'std::optionals?': r'https://en.cppreference.com/w/cpp/utility/optional',
        r'std::pairs?': r'https://en.cppreference.com/w/cpp/utility/pair',
        r'std::popcount(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/popcount',
        r'std::remove_cv(?:_t)?': r'https://en.cppreference.com/w/cpp/types/remove_cv',
        r'std::remove_reference(?:_t)?': r'https://en.cppreference.com/w/cpp/types/remove_reference',
        r'std::reverse_iterator': r'https://en.cppreference.com/w/cpp/iterator/reverse_iterator',
        r'std::runtime_errors?': r'https://en.cppreference.com/w/cpp/error/runtime_error',
        r'std::sets?': r'https://en.cppreference.com/w/cpp/container/set',
        r'std::shared_ptrs?': r'https://en.cppreference.com/w/cpp/memory/shared_ptr',
        r'std::sin[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/sin',
        r'std::spans?': r'https://en.cppreference.com/w/cpp/container/span',
        r'std::sqrt[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/sqrt',
        r'std::tan[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/tan',
        r'std::to_address(?:\(\))?': r'https://en.cppreference.com/w/cpp/memory/to_address',
        r'std::(?:true|false)_type': r'https://en.cppreference.com/w/cpp/types/integral_constant',
        r'std::trunc[fl]?(?:\(\))?': r'https://en.cppreference.com/w/cpp/numeric/math/trunc',
        r'std::tuple_element(?:_t)?': r'https://en.cppreference.com/w/cpp/utility/tuple/tuple_element',
        r'std::tuple_size(?:_v)?': r'https://en.cppreference.com/w/cpp/utility/tuple/tuple_size',
        r'std::tuples?': r'https://en.cppreference.com/w/cpp/utility/tuple',
        r'std::type_identity(?:_t)?': r'https://en.cppreference.com/w/cpp/types/type_identity',
        r'std::underlying_type(?:_t)?': r'https://en.cppreference.com/w/cpp/types/underlying_type',
        r'std::unique_ptrs?': r'https://en.cppreference.com/w/cpp/memory/unique_ptr',
        r'std::unordered_maps?': r'https://en.cppreference.com/w/cpp/container/unordered_map',
        r'std::unordered_sets?': r'https://en.cppreference.com/w/cpp/container/unordered_set',
        r'std::vectors?': r'https://en.cppreference.com/w/cpp/container/vector',
        r'std::atomic[a-zA-Z_0-9]*': r'https://en.cppreference.com/w/cpp/atomic/atomic',
        r'std::to_underlying(?:\(\))?': r'https://en.cppreference.com/w/cpp/utility/to_underlying',
        r'std::move_only_functions?': r'https://en.cppreference.com/w/cpp/utility/functional/move_only_function',
        # named requirements
        r'Allocators?': r'https://en.cppreference.com/w/cpp/named_req/Allocator',
        r'AllocatorAwareContainers?': r'https://en.cppreference.com/w/cpp/named_req/AllocatorAwareContainer',
        r'AssociativeContainers?': r'https://en.cppreference.com/w/cpp/named_req/AssociativeContainer',
        r'BasicFormatters?': r'https://en.cppreference.com/w/cpp/named_req/BasicFormatter',
        r'BasicLockables?': r'https://en.cppreference.com/w/cpp/named_req/BasicLockable',
        r'(?:Legacy)?BidirectionalIterators?': r'https://en.cppreference.com/w/cpp/named_req/BidirectionalIterator',
        r'BinaryPredicates?': r'https://en.cppreference.com/w/cpp/named_req/BinaryPredicate',
        r'BinaryTypeTraits?': r'https://en.cppreference.com/w/cpp/named_req/BinaryTypeTrait',
        r'BitmaskTypes?': r'https://en.cppreference.com/w/cpp/named_req/BitmaskType',
        r'Callables?': r'https://en.cppreference.com/w/cpp/named_req/Callable',
        r'CharTraits?': r'https://en.cppreference.com/w/cpp/named_req/CharTraits',
        r'Compares?': r'https://en.cppreference.com/w/cpp/named_req/Compare',
        r'(?:Legacy)?ConstexprIterators?': r'https://en.cppreference.com/w/cpp/named_req/ConstexprIterator',
        r'Containers?': r'https://en.cppreference.com/w/cpp/named_req/Container',
        r'ContiguousContainers?': r'https://en.cppreference.com/w/cpp/named_req/ContiguousContainer',
        r'(?:Legacy)?ContiguousIterators?': r'https://en.cppreference.com/w/cpp/named_req/ContiguousIterator',
        r'CopyAssignables?': r'https://en.cppreference.com/w/cpp/named_req/CopyAssignable',
        r'CopyConstructibles?': r'https://en.cppreference.com/w/cpp/named_req/CopyConstructible',
        r'CopyInsertables?': r'https://en.cppreference.com/w/cpp/named_req/CopyInsertable',
        r'DefaultConstructibles?': r'https://en.cppreference.com/w/cpp/named_req/DefaultConstructible',
        r'DefaultInsertables?': r'https://en.cppreference.com/w/cpp/named_req/DefaultInsertable',
        r'Destructibles?': r'https://en.cppreference.com/w/cpp/named_req/Destructible',
        r'EmplaceConstructibles?': r'https://en.cppreference.com/w/cpp/named_req/EmplaceConstructible',
        r'EqualityComparables?': r'https://en.cppreference.com/w/cpp/named_req/EqualityComparable',
        r'Erasables?': r'https://en.cppreference.com/w/cpp/named_req/Erasable',
        r'FormattedInputFunctions?': r'https://en.cppreference.com/w/cpp/named_req/FormattedInputFunction',
        r'FormattedOutputFunctions?': r'https://en.cppreference.com/w/cpp/named_req/FormattedOutputFunction',
        r'(?:Legacy)?ForwardIterators?': r'https://en.cppreference.com/w/cpp/named_req/ForwardIterator',
        r'FunctionObjects?': r'https://en.cppreference.com/w/cpp/named_req/FunctionObject',
        r'ImplicitLifetimeTypes?': r'https://en.cppreference.com/w/cpp/named_req/ImplicitLifetimeType',
        r'LegacyIterators?': r'https://en.cppreference.com/w/cpp/named_req/LegacyIterator',
        r'(?:Legacy)?InputIterators?': r'https://en.cppreference.com/w/cpp/named_req/InputIterator',
        r'(?:Legacy)?Iterators?': r'https://en.cppreference.com/w/cpp/named_req/Iterator',
        r'LessThanComparables?': r'https://en.cppreference.com/w/cpp/named_req/LessThanComparable',
        r'LiteralTypes?': r'https://en.cppreference.com/w/cpp/named_req/LiteralType',
        r'Lockables?': r'https://en.cppreference.com/w/cpp/named_req/Lockable',
        r'MoveAssignables?': r'https://en.cppreference.com/w/cpp/named_req/MoveAssignable',
        r'MoveConstructibles?': r'https://en.cppreference.com/w/cpp/named_req/MoveConstructible',
        r'MoveInsertables?': r'https://en.cppreference.com/w/cpp/named_req/MoveInsertable',
        r'NullablePointers?': r'https://en.cppreference.com/w/cpp/named_req/NullablePointer',
        r'NumericTypes?': r'https://en.cppreference.com/w/cpp/named_req/NumericType',
        r'(?:Legacy)?OutputIterators?': r'https://en.cppreference.com/w/cpp/named_req/OutputIterator',
        r'PODTypes?': r'https://en.cppreference.com/w/cpp/named_req/PODType',
        r'Predicates?': r'https://en.cppreference.com/w/cpp/named_req/Predicate',
        r'(?:Legacy)?RandomAccessIterators?': r'https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator',
        r'RandomNumberDistributions?': r'https://en.cppreference.com/w/cpp/named_req/RandomNumberDistribution',
        r'RandomNumberEngines?': r'https://en.cppreference.com/w/cpp/named_req/RandomNumberEngine',
        r'RandomNumberEngineAdaptors?': r'https://en.cppreference.com/w/cpp/named_req/RandomNumberEngineAdaptor',
        r'RangeAdaptorClosureObjects?': r'https://en.cppreference.com/w/cpp/named_req/RangeAdaptorClosureObject',
        r'RangeAdaptorObjects?': r'https://en.cppreference.com/w/cpp/named_req/RangeAdaptorObject',
        r'RegexTraitss?': r'https://en.cppreference.com/w/cpp/named_req/RegexTraits',
        r'ReversibleContainers?': r'https://en.cppreference.com/w/cpp/named_req/ReversibleContainer',
        r'ScalarTypes?': r'https://en.cppreference.com/w/cpp/named_req/ScalarType',
        r'SeedSequences?': r'https://en.cppreference.com/w/cpp/named_req/SeedSequence',
        r'SequenceContainers?': r'https://en.cppreference.com/w/cpp/named_req/SequenceContainer',
        r'SharedLockables?': r'https://en.cppreference.com/w/cpp/named_req/SharedLockable',
        r'SharedMutexes?': r'https://en.cppreference.com/w/cpp/named_req/SharedMutex',
        r'SharedTimedLockables?': r'https://en.cppreference.com/w/cpp/named_req/SharedTimedLockable',
        r'SharedTimedMutexes?': r'https://en.cppreference.com/w/cpp/named_req/SharedTimedMutex',
        r'StandardLayoutTypes?': r'https://en.cppreference.com/w/cpp/named_req/StandardLayoutType',
        r'Swappables?': r'https://en.cppreference.com/w/cpp/named_req/Swappable',
        r'TimedLockables?': r'https://en.cppreference.com/w/cpp/named_req/TimedLockable',
        r'TimedMutexes?': r'https://en.cppreference.com/w/cpp/named_req/TimedMutex',
        r'TransformationTraits?': r'https://en.cppreference.com/w/cpp/named_req/TransformationTrait',
        r'TrivialClocks?': r'https://en.cppreference.com/w/cpp/named_req/TrivialClock',
        r'TriviallyCopyables?': r'https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable',
        r'TrivialTypes?': r'https://en.cppreference.com/w/cpp/named_req/TrivialType',
        r'UnaryTypeTraits?': r'https://en.cppreference.com/w/cpp/named_req/UnaryTypeTrait',
        r'UnformattedInputFunctions?': r'https://en.cppreference.com/w/cpp/named_req/UnformattedInputFunction',
        r'UnformattedOutputFunctions?': r'https://en.cppreference.com/w/cpp/named_req/UnformattedOutputFunction',
        r'UniformRandomBitGenerators?': r'https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator',
        r'UnorderedAssociativeContainers?': r'https://en.cppreference.com/w/cpp/named_req/UnorderedAssociativeContainer',
        r'ValueSwappables?': r'https://en.cppreference.com/w/cpp/named_req/ValueSwappable',
        # other misc cppreference pages
        r'(?:RAII|[Rr]esource[ -][Aa]cquisition[ -][Ii]s[ -][Ii]nitiali[sz]ation(?: \(RAII\))?)': r'https://en.cppreference.com/w/cpp/language/raii',
        r'(?:CRTP|[Cc]uriously[ -][Rr]ecurring[ -][Tt]emplate[ -][Pp]attern(?: \(CRTP\))?)': r'https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern',
        r'(?:CTAD|[Cc]lass[ -][Tt]emplate[ -][Aa]rgument[ -][Dd]eduction(?: \(CTAD\))?)': r'https://en.cppreference.com/w/cpp/language/class_template_argument_deduction',
        r'(?:EBC?O|[Ee]mpty[ -][Bb]ase[ -](?:[Cc]lass[ -])?[Oo]ptimi[sz]ations?(?: \(EBC?O\))?)': r'https://en.cppreference.com/w/cpp/language/ebo',
        r'(?:UDLs?|[Uu]ser[ -][Dd]efined[ -][Ll]iterals?(?:[ -][Oo]perators?)?(?: \(UDLs?\))?)': r'https://en.cppreference.com/w/cpp/language/user_literal',
        r'(?:N?RVO|[Cc]opy[ -][Ee]lision|(?:[Nn]amed[ -])?[Rr]eturn[ -][Vv]alue[ -][Oo]ptimi[sz]ations?(?: \(N?RVO\))?)': r'https://en.cppreference.com/w/cpp/language/copy_elision',
        r'INVOKE(?:(?:<|&lt;)R(?:>|&gt;))?(?: [Ee]xpressions?)?': r'https://en.cppreference.com/w/cpp/utility/functional',
        # windows
        r'(?:L?P)?(?:'
        + r'D?WORD(?:32|64|_PTR)?|HANDLE|HMODULE|BOOL(?:EAN)?'
        + r'|U?SHORT|U?LONG|U?INT(?:8|16|32|64)?'
        + r'|BYTE|VOID|C[WT]?STR'
        + r')': r'https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types',
        r'__INTELLISENSE__|_MSC(?:_FULL)_VER|_MSVC_LANG|_WIN(?:32|64)': r'https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019',
        r'IUnknowns?': r'https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iunknown',
        r'(?:IUnknown::)?QueryInterface?': r'https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nf-unknwn-iunknown-queryinterface(q)',
        # unreal engine types
        r'(?:::)?FBox(?:es)?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FBox/index.html',
        r'(?:::)?FBox2Ds?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FBox2D/index.html',
        r'(?:::)?FColors?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FColor/index.html',
        r'(?:::)?FFloat16s?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FFloat16/index.html',
        r'(?:::)?FFloat32s?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FFloat32/index.html',
        r'(?:::)?FMatrix(?:es|ices)?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FMatrix/index.html',
        r'(?:::)?FMatrix2x2s?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FMatrix2x2/index.html',
        r'(?:::)?FOrientedBox(?:es)?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FOrientedBox/index.html',
        r'(?:::)?FPlanes?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FPlane/index.html',
        r'(?:::)?FQuat2Ds?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FQuat2D/index.html',
        r'(?:::)?FQuats?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FQuat/index.html',
        r'(?:::)?FStrings?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Containers/FString/index.html',
        r'(?:::)?FVector2DHalfs?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FVector2DHalf/index.html',
        r'(?:::)?FVector2Ds?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FVector2D/index.html',
        r'(?:::)?FVector4s?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FVector4/index.html',
        r'(?:::)?FVectors?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FVector/index.html',
        r'(?:::)?TMatrix(?:es|ices)?': r'https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/TMatrix/index.html',
        r'(?:::)?UStaticMesh(?:es)?': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/Engine/UStaticMesh/',
        r'(?:::)?FStaticMeshLODResources': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/FStaticMeshLODResources/',
        r'(?:::)?FRawStaticIndexBuffer(?:s)?': r'https://docs.unrealengine.com/4.26/en-US/API/Runtime/Engine/FRawStaticIndexBuffer/',
        r'(?:::)?FStaticMeshVertexBuffers': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/FStaticMeshVertexBuffers/',
        r'(?:::)?FStaticMeshVertexBuffer': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/Rendering/FStaticMeshVertexBuffer/',
        r'(?:::)?FPositionVertexBuffer(?:s)?': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/Rendering/FPositionVertexBuffer/',
        r'(?:::)?TArrayView(?:s)?': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Core/Containers/TArrayView/',
        r'(?:::)?TArray(?:s)?': r'https://docs.unrealengine.com/4.27/en-US/API/Runtime/Core/Containers/TArray/',
        # fmtlib
        r'fmt::(?:v?format(?:_string|_to|ted_size|ter)?|memory_buffer|string_view|runtime|print|to_w?string|underlying|ptr|emphasis|styled)s?': 'https://fmt.dev/latest/api.html',
    }
    navbar = (r'files', r'macros', r'groups', r'namespaces', r'classes', r'concepts')
    navbar_all = (r'pages', r'blog', *navbar, r'repo', r'theme')
    aliases = {
        # poxy
        r'cpp': r'@code{.cpp}',
        r'ecpp': r'@endcode',
        r'endcpp': r'@endcode',
        r'out': r'@code{.shell-session}',
        r'eout': r'@endcode',
        r'endout': r'@endcode',
        r'python': r'@code{.py}',
        r'epython': r'@endcode',
        r'endpython': r'@endcode',
        r'meson': r'@code{.py}',
        r'emeson': r'@endcode',
        r'endmeson': r'@endcode',
        r'cmake': r'@code{.cmake}',
        r'ecmake': r'@endcode',
        r'endcmake': r'@endcode',
        r'javascript': r'@code{.js}',
        r'ejavascript': r'@endcode',
        r'endjavascript': r'@endcode',
        r'json': r'@code{.js}',
        r'ejson': r'@endcode',
        r'endjson': r'@endcode',
        r'shell': r'@code{.shell-session}',
        r'eshell': r'@endcode',
        r'endshell': r'@endcode',
        r'bash': r'@code{.sh}',
        r'ebash': r'@endcode',
        r'endbash': r'@endcode',
        r'detail': r'@details',
        r'conditional_return{1}': r'<strong><em>\1:</em></strong> ',
        r'inline_attention': r'[set_class m-note m-warning]',
        r'inline_note': r'[set_class m-note m-info]',
        r'inline_remark': r'[set_class m-note m-default]',
        r'inline_subheading{1}': r'[h4]\1[/h4]',
        r'inline_success': r'[set_class m-note m-success]',
        r'inline_warning': r'[set_class m-note m-danger]',
        r'github{1}': r'<a href="https://github.com/\1" target="_blank">\1</a>',
        r'github{2}': r'<a href="https://github.com/\1" target="_blank">\2</a>',
        r'gitlab{1}': r'<a href="https://gitlab.com/\1" target="_blank">\1</a>',
        r'gitlab{2}': r'<a href="https://gitlab.com/\1" target="_blank">\2</a>',
        r'godbolt{1}': r'<a href="https://godbolt.org/z/\1" target="_blank">Try this code on Compiler Explorer</a>',
        r'flags_enum': r'@note This enum is a flags type; it is equipped with a full complement of bitwise operators. ^^',
        r'implementers': r'@par [parent_parent_set_class m-block m-dim][emoji hammer][entity nbsp]Implementers: ',
        r'optional': r'@par [parent_parent_set_class m-block m-info]Optional field ^^',
        r'required': r'@par [parent_parent_set_class m-block m-warning][emoji warning][entity nbsp]Required field ^^',
        r'availability': r'@par [parent_parent_set_class m-block m-special]Conditional availability ^^',
        r'figure{1}': r'@image html \1',
        r'figure{2}': r'@image html \1 "\2"',
        # video embeds. nocookie is youtube's own privacy-preserving host for exactly this
        r'youtube{1}': r'@htmlonly[block]<div class="poxy-video"><iframe src="https://www.youtube-nocookie.com/embed/\1" title="YouTube video" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>@endhtmlonly',
        r'youtube{2}': r'@htmlonly[block]<div class="poxy-video"><iframe src="https://www.youtube-nocookie.com/embed/\1" title="\2" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>@endhtmlonly',
        # tabbed content blocks (restructured by the TabBlocks html fixer)
        r'tabs': r'[tabs]',
        r'etabs': r'[/tabs]',
        r'endtabs': r'[/tabs]',
        r'tab{1}': r'[tab \1]',
        # m.css
        r'm_div{1}': r'@xmlonly<mcss:div xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:class="\1">@endxmlonly',
        r'm_enddiv': r'@xmlonly</mcss:div>@endxmlonly',
        r'm_span{1}': r'@xmlonly<mcss:span xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:class="\1">@endxmlonly',
        r'm_endspan': r'@xmlonly</mcss:span>@endxmlonly',
        r'm_class{1}': r'@xmlonly<mcss:class xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:class="\1" />@endxmlonly',
        r'm_footernavigation': r'@xmlonly<mcss:footernavigation xmlns:mcss="http://mcss.mosra.cz/doxygen/" />@endxmlonly',
        r'm_examplenavigation{2}': r'@xmlonly<mcss:examplenavigation xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:page="\1" mcss:prefix="\2" />@endxmlonly',
        r'm_keywords{1}': r'@xmlonly<mcss:search xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:keywords="\1" />@endxmlonly',
        r'm_keyword{3}': r'@xmlonly<mcss:search xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:keyword="\1" mcss:title="\2" mcss:suffix-length="\3" />@endxmlonly',
        r'm_enum_values_as_keywords': r'@xmlonly<mcss:search xmlns:mcss="http://mcss.mosra.cz/doxygen/" mcss:enum-values-as-keywords="true" />@endxmlonly',
    }
    source_patterns = {
        r'*.h',
        r'*.hh',
        r'*.hxx',
        r'*.hpp',
        r'*.h++',
        r'*.ixx',
        r'*.inc',
        r'*.markdown',
        r'*.md',
        r'*.dox',
    }
    # code block syntax highlighting only
    #
    # note: we don't need to be comprehensive for the std namespace symbols;
    # those will get added from the cppreference tagfile
    cb_enums = {r'(?:std::)?ios(?:_base)?::(?:app|binary|in|out|trunc|ate)'}
    cb_macros = {
        # standard builtins:
        r'__cplusplus(?:_cli|_winrt)?',
        r'__cpp_[a-zA-Z_]+?',
        r'__has_(?:(?:cpp_)?attribute|include)',
        r'assert',
        r'offsetof',
        # poxy:
        r'POXY_[a-zA-Z_]+',
        # compiler builtins:
        regex_trie(
            # standard:
            r'__FILE__',
            r'__LINE__',
            r'__DATE__',
            r'__TIME__',
            r'__STDC__',
            r'__STDC_HOSTED__',
            r'__STDC_VERSION__',
            r'__STDC_ISO_10646__',
            r'__STDC_MB_MIGHT_NEQ_WC__',
            r'__STDCPP_THREADS__',
            r'__STDCPP_DEFAULT_NEW_ALIGNMENT__',
            r'__STDCPP_STRICT_POINTER_SAFETY__',
            # msvc:
            r'_ATL_VER',  #
            r'_CHAR_UNSIGNED',
            r'_CONTROL_FLOW_GUARD',
            r'_CPPRTTI',
            r'_CPPUNWIND',
            r'_DEBUG',
            r'_DLL',
            r'_INTEGRAL_MAX_BITS',
            r'_ISO_VOLATILE',
            r'_KERNEL_MODE',
            r'_MANAGED',
            r'_MFC_VER',
            r'_MSC_BUILD',
            r'_MSC_EXTENSIONS',
            r'_MSC_FULL_VER',
            r'_MSC_VER',
            r'_MSVC_LANG',
            r'_MSVC_TRADITIONAL',
            r'_MT',
            r'_M_AMD64',
            r'_M_ARM',
            r'_M_ARM64',
            r'_M_ARM64EC',
            r'_M_ARM_ARMV7VE',
            r'_M_ARM_FP',
            r'_M_CEE',
            r'_M_CEE_PURE',
            r'_M_CEE_SAFE',
            r'_M_FP_CONTRACT',
            r'_M_FP_EXCEPT',
            r'_M_FP_FAST',
            r'_M_FP_PRECISE',
            r'_M_FP_STRICT',
            r'_M_IX86',
            r'_M_IX86_FP',
            r'_M_X64',
            r'_NATIVE_WCHAR_T_DEFINED',
            r'_OPENMP',
            r'_PREFAST_',
            r'_VC_NODEFAULTLIB',
            r'_WCHAR_T_DEFINED',
            r'_WIN32',
            r'_WIN64',
            r'_WINRT_DLL',
            r'__ATOM__',
            r'__AVX2__',
            r'__AVX512BW__',
            r'__AVX512CD__',
            r'__AVX512DQ__',
            r'__AVX512F__',
            r'__AVX512VL__',
            r'__AVX__',
            r'__CLR_VER',
            r'__COUNTER__',
            r'__FUNCDNAME__',
            r'__FUNCSIG__',
            r'__FUNCTION__',
            r'__INTELLISENSE__',
            r'__MSVC_RUNTIME_CHECKS',
            r'__SANITIZE_ADDRESS__',
            r'__STDC_NO_ATOMICS__',
            r'__STDC_NO_COMPLEX__',
            r'__STDC_NO_THREADS__',
            r'__STDC_NO_VLA__',
            r'__TIMESTAMP__',
            r'__cplusplus_cli',
            r'__cplusplus_winrt',
            r'NDEBUG',
            r'_DEBUG',
        ),
    }
    cb_namespaces = {
        regex_trie(
            r'std',
            r'std::chrono',
            r'std::execution',
            r'std::filesystem',
            r'std::experimental',
            r'std::numbers',
            r'std::literals',
            r'std::literals::chrono_literals',
            r'std::literals::complex_literals',
            r'std::literals::string_literals',
            r'std::literals::string_view_literals',
            r'std::chrono_literals',
            r'std::complex_literals',
            r'std::string_literals',
            r'std::string_view_literals',
            r'std::ranges',
            r'std::this_thread',
        )
    }
    cb_types = {
        # ------ built-in types
        r'__(?:float|fp)[0-9]{1,3}',
        r'__m[0-9]{1,3}[di]?',
        r'_Float[0-9]{1,3}',
        r'[a-zA-Z_][a-zA-Z_0-9]*_t(?:ype(?:def)?|raits)?',
        regex_trie(r'bool', r'char', r'double', r'float', r'int', r'long', r'short', r'signed', r'unsigned'),
        # ------ documentation-only types
        r'(?:[a-zA-Z][a-zA-Z_]+::)*?(?:[a-zA-Z][a-zA-Z_]+_type|Foo|Bar|[Vv]ec(?:tor)?[1-4][hifd]?|[Mm]at(?:rix)?[1-4](?:[xX][1-4])?[hifd]?)',
        r'[S-Z][0-9]?',
    }
    cb_functions = {regex_trie(r'std::as_const', r'std::move', r'std::forward')}
