#!/usr/bin/env python3
# This file is a part of marzer/poxy and is subject to the the terms of the MIT license.
# Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
# See https://github.com/marzer/poxy/blob/master/LICENSE for the full license text.
# SPDX-License-Identifier: MIT
"""
Standalone markdown input filter, wired into Doxygen via FILTER_PATTERNS so it runs uniformly on every
markdown file Doxygen reads (not just the special main_page/changelog temp copies). Doxygen invokes it as
`<this> <file>` and reads the transformed content from stdout.

Kept dependency-free (stdlib only) and free of any `poxy` package import so it starts fast when spawned
once per file. The pure functions are unit-tested directly.
"""

import re
import sys

SENTINEL_AMP = r'poxyentityamp'
SENTINEL_AT = r'poxyentityat'
SENTINEL_HEX = r'poxyentityhex'  # immediately followed by the entity's hex digits

_TOC_BULLET = re.compile(r'^[ \t]*[-*+][ \t]+\[[^\]]+\]\(#[^)\s]*\)[ \t]*$')
_TOC_DIRECTIVE = re.compile(r'(?m)^[ \t]*(?:[@\\]tableofcontents\b|\[TOC\][ \t]*$)')

# doxygen omits the <tableofcontents> XML element for the HTML-generator-specific '@tableofcontents{HTML:N}'
# form and for markdown's '[TOC]', so m.css (which works from the XML) renders no TOC nav for those.
_TOC_HTML_LEVEL = re.compile(r'(?m)^([ \t]*)[@\\]tableofcontents\{[^}]*\bHTML:(\d+)[^}]*\}[ \t]*$')
_TOC_MARKDOWN = re.compile(r'(?m)^([ \t]*)\[TOC\][ \t]*$')


def normalize_toc_directives(text: str) -> str:
    """Retarget TOC directives doxygen would drop from XML so it emits <tableofcontents> (which m.css needs):
    '@tableofcontents{HTML:N}' -> '@tableofcontents{XML:N}' (doxygen then emits it, pruned to N levels), and
    markdown '[TOC]' -> '@tableofcontents' (full depth)."""
    text = _TOC_HTML_LEVEL.sub(r'\1@tableofcontents{XML:\2}', text)
    text = _TOC_MARKDOWN.sub(r'\1@tableofcontents', text)
    return text


def strip_handrolled_toc(text: str) -> str:
    """Remove a hand-authored bullet-list table of contents - a contiguous run of list items that are each
    nothing but an in-page anchor link - and, if the document then has no TOC directive, insert an
    @tableofcontents where the list was so poxy still renders its styled TOC nav.

    Such lists are common in GitHub READMEs (auto-generated by various editors) but duplicate the TOC poxy
    builds from @tableofcontents, and their GitHub-style slug links do not resolve against doxygen's own
    heading anchors anyway."""
    lines = text.split('\n')

    # find the first maximal run of >= 2 consecutive TOC-bullet lines
    start = end = None
    i = 0
    while i < len(lines):
        if _TOC_BULLET.match(lines[i]):
            j = i
            while j < len(lines) and _TOC_BULLET.match(lines[j]):
                j += 1
            if j - i >= 2:
                start, end = i, j
                break
            i = j
        else:
            i += 1
    if start is None:
        return text

    replacement = []
    if not _TOC_DIRECTIVE.search(text):
        replacement = [r'@tableofcontents']
    out = '\n'.join(lines[:start] + replacement + lines[end:])
    out = re.sub(r'\n{3,}', '\n\n', out)
    return out


def protect_entities(text: str) -> str:
    """Hide HTML entities behind sentinels so doxygen does not mangle them (it otherwise turns a numeric
    character reference like &#x2764; into the literal text &amp;#x2764;). The post-process
    RestoreMarkdownSentinels fixer turns these back into the real entities in the final HTML."""
    text = text.replace(r'&amp;', SENTINEL_AMP)
    text = re.sub(r'&#x([a-fA-F0-9]{2,4});', rf'{SENTINEL_HEX}\1', text)
    return text


def preprocess(text: str) -> str:
    return strip_handrolled_toc(normalize_toc_directives(protect_entities(text)))


def main() -> int:
    if len(sys.argv) < 2:
        return 1
    with open(sys.argv[1], encoding=r'utf-8') as f:
        text = f.read()
    sys.stdout.write(preprocess(text))
    return 0


if __name__ == r'__main__':
    sys.exit(main())
